// Ambient canvas blossom background for GAYA.
// Extracted from the original single-file prototype.
(function(){
function initPageBlooms(){const canvas=document.getElementById('pageBlooms');if(!canvas)return;const ctx=canvas.getContext('2d');const palettes=[['#E24B4A','#EF9F27','#F0997B','#FAC775','#D4537E'],['#F4C0D1','#FAC775','#9FE1CB','#B5D4F4','#CECBF6'],['#7F77DD','#534AB7','#D85A30','#EF9F27','#993556'],['#9FE1CB','#5DCAA5','#C0DD97','#FAC775','#F4C0D1']];let blooms=[],W=0,H=0,dpr=1;function makeFlower(x,y,edge){const palette=palettes[Math.floor(Math.random()*palettes.length)];const colorIdx=Math.floor(Math.random()*palette.length);return{x,y,petalCount:5+Math.floor(Math.random()*6),petalSize:(edge?6:4)+Math.random()*(edge?9:6),color:palette[colorIdx],centerColor:palette[(colorIdx+2)%palette.length],rotation:Math.random()*Math.PI*2,alpha:edge?.55+Math.random()*.18:.22+Math.random()*.2};}function scatter(){const count=Math.min(150,Math.max(70,Math.floor(W*H/15000)));blooms=[];for(let i=0;i<count;i++){const edge=Math.random()<.66;let x,y;if(edge){const side=Math.floor(Math.random()*4);if(side===0){x=Math.random()*W;y=16+Math.random()*120;}else if(side===1){x=W-16-Math.random()*150;y=Math.random()*H;}else if(side===2){x=Math.random()*W;y=H-16-Math.random()*150;}else{x=16+Math.random()*150;y=Math.random()*H;}}else{x=Math.random()*W;y=Math.random()*H;}blooms.push(makeFlower(x,y,edge));}}function draw(){ctx.clearRect(0,0,W,H);for(const f of blooms){ctx.save();ctx.globalAlpha=f.alpha;ctx.fillStyle=f.color;for(let i=0;i<f.petalCount;i++){const angle=f.rotation+(i/f.petalCount)*Math.PI*2;const px=f.x+Math.cos(angle)*f.petalSize*.9;const py=f.y+Math.sin(angle)*f.petalSize*.9;ctx.beginPath();ctx.arc(px,py,f.petalSize,0,Math.PI*2);ctx.fill();}ctx.fillStyle=f.centerColor;ctx.beginPath();ctx.arc(f.x,f.y,f.petalSize*.55,0,Math.PI*2);ctx.fill();ctx.restore();}}function resize(){dpr=window.devicePixelRatio||1;W=window.innerWidth;H=window.innerHeight;canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);scatter();draw();}window.addEventListener('resize',resize);resize();}
window.initPageBlooms=initPageBlooms;

// Temporary bootstrap for small app enhancements while index.html still owns the main app script.
// When the app script is extracted, this should move into index.html as a normal script tag.
const enhancement=document.createElement('script');
enhancement.src='gaya-enhancements.js';
enhancement.defer=true;
document.head.appendChild(enhancement);
})();